### ISSUE TITLE
跳了个寂寞

### ISSUE THREAD

**Issue by chenyixin8854** [fuzhengwei/MonitorDesign#1]
源码呢？速速滴

**Comment by fuzhengwei** [comment]
今晚更新，等待下

**Comment by gyety** [comment]
寂寞寂寞就好

**Comment by gwweng** [comment]
字节码插桩在IDEA设置好javaagent后没有生效，请问小傅哥这是为啥

**Comment by fuzhengwei** [comment]
> 字节码插桩在IDEA设置好javaagent后没有生效，请问小傅哥这是为啥

把对应的字节码插桩Jar包引入到pom里，删除其他的。
